
CREATE SCHEMA Settings
CREATE TABLE [Settings].[District]
(
	[RowId]				[BIGINT]	   NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[DistrictId]		[INT]		   NULL,
	[ProvinceId]		[INT]		   NULL,
	[DistrictName]		[VARCHAR](30)  NULL,
	[DistrictNameLocal] [NVARCHAR](30) NULL,
	[Headquarter]		[NVARCHAR](50) NULL,
	[HeadquarterLocal]	[NVARCHAR](50) NULL,
	[AreaSqKm]			[NVARCHAR](50) NULL,
	[AreaSqKmLocal]		[NVARCHAR](50) NULL,
	[Website]			[NVARCHAR](50) NULL,
	[IsActive]			[BIT]		   NULL,
	[CreatedBy]			[VARCHAR](30)  NULL,
	[CreatedDate]		[DATETIME]	   NULL,
	[ModifiedBy]		[VARCHAR](30)  NULL,
	[ModifiedDate]		[DATETIME]	   NULL
);

INSERT INTO [Settings].[District] ([DistrictId], [ProvinceId], [DistrictName], [DistrictNameLocal], [Headquarter], [HeadquarterLocal], [AreaSqKm], [AreaSqKmLocal], [Website], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate])
VALUES
(1, 1, 'Bhojpur', N'भोजपुर', N'Bhojpur', N'भोजपुर', N'1507', N'१५०७', N'https://www.ddcbhojpur.gov.np', NULL, NULL, NULL, NULL, NULL ),
(2, 1, 'Dhankuta', N'धनकुटा', N'Dhankuta', N'धनकुटा', N'892', N'८९२', N'https://www.ddcdhankuta.gov.np', NULL, NULL, NULL, NULL, NULL ),
(3, 1, 'Ilam', N'इलाम', N'Ilam', N'ईलाम', N'1703', N'१७०३', N'https://www.ddcilam.gov.np', NULL, NULL, NULL, NULL, NULL ),
(4, 1, 'Jhapa', N'झापा', N'Bhadrapur', N'झापा', N'1606', N'१६०६', N'https://www.ddcjhapa.gov.np', NULL, NULL, NULL, NULL, NULL ),
(5, 1, 'Khotang', N'खोटाँग', N'Diktel', N'खोटांग', N'1591', N'१५९१', N'https://www.dcckhotang.gov.np', NULL, NULL, NULL, NULL, NULL ),
(6, 1, 'Morang', N'मोरंग', N'Biratnagar', N'मोरंग', N'1855', N'१८५५', N'https://www.ddcmorang.gov.np', NULL, NULL, NULL, NULL, NULL ),
(7, 1, 'Okhaldhunga', N'ओखलढुंगा', N'Siddhicharan', N'सिद्धिचरण', N'1074', N'१०७४', N'https://www.dccokhaldhunga.gov.np/en', NULL, NULL, NULL, NULL, NULL ),
(8, 1, 'Pachthar', N'पांचथर', N'Phidim', N'फिदिम', N'1241', N'१२४१', N'https://www.ddcpanchthar.gov.np', NULL, NULL, NULL, NULL, NULL ),
(9, 1, 'Sankhuwasabha', N'संखुवासभा', N'Khandbari', N'खाँदबारी', N'3480', N'३४८०', N'https://www.ddcsankhuwasabha.gov.np', NULL, NULL, NULL, NULL, NULL ),
(10, 1, 'Solukhumbu', N'सोलुखुम्बू', N'Salleri', N'सल्लेरी', N'3312', N'३३१२', N'https://www.ddcsolukhumbu.gov.np', NULL, NULL, NULL, NULL, NULL ),
(11, 1, 'Sunsari', N'सुनसरी', N'Inaruwa', N'इनरुवा', N'1257', N'१२५७', N'https://www.ddcsunsari.gov.np', NULL, NULL, NULL, NULL, NULL ),
(12, 1, 'Taplejung', N'ताप्लेजुंग', N'Taplejung', N'ताप्लेजुंग', N'3646', N'३६४६', N'https://www.ddctaplejung.gov.np', NULL, NULL, NULL, NULL, NULL ),
(13, 1, 'Terhathum', N'तेह्रथुम', N'Myanglung', N'म्यांगलुङ्ग', N'679', N'६७९', N'https://www.ddctehrathum.gov.np', NULL, NULL, NULL, NULL, NULL ),
(14, 1, 'Udayapur', N'उदयपुर', N'Gaighat', N'गाईघाट', N'2063', N'२०६३', N'https://www.ddcudayapur.gov.np', NULL, NULL, NULL, NULL, NULL ),
(15, 2, 'Parsa', N'पर्सा', N'Birgunj', N'विरगंज', N'1353', N'१३५३', N'https://dccparsa.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(16, 2, 'Bara', N'बारा', N'Kalaiya', N'कलैया', N'1190', N'११९०', N'https://dccbara.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(17, 2, 'Rautahat', N'रौतहट', N'Gaur', N'गौर', N'1126', N'११२६', N'https://dccrautahat.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(18, 2, 'Sarlahi', N'सर्लाही', N'Malangawa', N'मलंगवा', N'1259', N'१२५९', N'https://dccsarlahi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(19, 2, 'Siraha', N'सिराहा', N'Siraha', N'सिरहा', N'1188', N'११८८', N'https://dccsiraha.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(20, 2, 'Dhanusha', N'धनुषा', N'Janakpur', N'जनकपुर', N'1180', N'११८०', N'https://dccdhanusha.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(21, 2, 'Saptari', N'सप्तरी', N'Rajbiraj', N'राजविराज', N'1363', N'१३६३', N'https://dccsaptari.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(22, 2, 'Mahottari', N'महोत्तरी', N'Jaleshwar', N'जलेश्वर', N'1002', N'१००२', N'https://dccmahottari.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(23, 3, 'Bhaktapur', N'भक्तपुर', N'Bhaktapur', N'भक्तपुर', N'119', N'११९', N'https://dccbhaktapur.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(24, 3, 'Chitwan', N'चितवन', N'Bharatpur', N'भरतपुर', N'2218', N'२२१८', N'https://dccchitwan.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(25, 3, 'Dhading', N'धादिंङ्ग', N'Nilkantha', N'निलकण्ठ', N'1926', N'१९२६', N'https://dccdhading.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(26, 3, 'Dolakha', N'दोलखा', N'Bhimeshwar', N'भिमेश्वर', N'2191', N'२१९१', N'https://dccdolakha.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(27, 3, 'Kathmandu', N'काठमाडौँ', N'Kathmandu', N'काठमाडौँ', N'395', N'३९५', N'https://dccktm.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(28, 3, 'Kavrepalanchok', N'काभ्रेपलान्चोक', N'Dhulikhel', N'धुलिखेल', N'1396', N'१३९६', N'https://dcckavre.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(29, 3, 'Lalitpur', N'ललितपुर', N'Lalitpur', N'ललितपुर', N'385', N'३८५', N'https://dcclalitpur.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(30, 3, 'Makwanpur', N'मकवानपुर', N'Hetauda', N'हेटौडा', N'2426', N'२४२६', N'https://dccmakwanpur.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(31, 3, 'Nuwakot', N'नुवाकोट', N'Bidur', N'बिदुर', N'1121', N'११२१', N'https://dccnuwakot.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(32, 3, 'Ramechap', N'रामेछाप', N'Manthali', N'मन्थली', N'1546', N'१५४६', N'https://dccramechhap.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(33, 3, 'Rasuwa', N'रसुवा', N'Dhunche', N'धुन्चे', N'1544', N'१५४४', N'https://dccrasuwa.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(34, 3, 'Sindhuli', N'सिन्धुली', N'Kamalamai', N'कमलामाई', N'2491', N'२४९१', N'https://dccsindhuli.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(35, 3, 'Sindhupalchok', N'सिन्धुपाल्चोक', N'Chautara', N'चौतारा', N'2542', N'२५४२', N'https://dccsindhupalchowk.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(36, 4, 'Baglung', N'बागलुङ', N'Baglung', N'बाग्लुंग', N'1784', N'१७८४', N'https://dccbaglung.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(37, 4, 'Gorkha', N'गोरखा', N'Gorkha', N'गोर्खा', N'3610', N'३६१०', N'https://dccgorkha.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(38, 4, 'Kaski', N'कास्की', N'Pokhara', N'पोखरा', N'2017', N'२०१७', N'https://dcckaski.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(39, 4, 'Lamjung', N'लमजुङ', N'Besisahar', N'बेशीसहर', N'1692', N'१६९२', N'https://dcclamjung.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(40, 4, 'Manang', N'मनाङ', N'Chame', N'चामे', N'2246', N'२२४६', N'https://dccmanang.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(41, 4, 'Mustang', N'मुस्ताङ', N'Jomsom', N'जोमसोम', N'3573', N'३५७३', N'https://dccmustang.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(42, 4, 'Myagdi', N'म्याग्दी', N'Beni', N'बेनी', N'2297', N'२२९७', N'https://dccmyagdi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(43, 4, 'Nawalpur', N'नवलपुर', N'Kawasoti', N'कावासोती', N'1043.1', N'१०४३.१', N'https://dccnawalparasi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(44, 4, 'Parwat', N'पर्वत', N'Kusma', N'कुस्मा', N'494', N'४९४', N'https://dccparbat.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(45, 4, 'Syangja', N'स्याङग्जा', N'Putalibazar', N'पुतलीबजार', N'1164', N'११६४', N'https://dccsyangja.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(46, 4, 'Tanahun', N'तनहुँ', N'Damauli', N'दमौली', N'1546', N'१५४६', N'https://dcctanahun.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(47, 5, 'Kapilvastu', N'कपिलवस्तु', N'Taulihawa', N'तौलिहवा', N'1738', N'१७३८', N'https://dcckapilvastu.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(48, 5, 'Parasi', N'परासी', N'Ramgram', N'रामग्राम', N'634.88', N'६३४.८८', N'https://dccnawalparasi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(49, 5, 'Rupandehi', N'रुपन्देही', N'Siddharthanagar', N'सिद्धार्थनगर', N'1360', N'१३६०', N'https://dccrupandehi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(50, 5, 'Arghakhanchi', N'अर्घाखाँची', N'Sandhikharka', N'सन्धिखर्क', N'1193', N'११९३', N'https://dccargakhanchi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(51, 5, 'Gulmi', N'गुल्मी', N'Tamghas', N'तम्घास', N'1149', N'११४९', N'https://dccgulmi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(52, 5, 'Palpa', N'पाल्पा', N'Tansen', N'तानसेन', N'1373', N'१३७३', N'https://dccpalpa.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(53, 5, 'Dang', N'दाङ', N'Ghorahi', N'घोराही', N'2955', N'२९५५', N'https://dccdang.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(54, 5, 'Pyuthan', N'प्युठान', N'Pyuthan', N'प्युठान', N'1309', N'१३०९', N'https://dccpyuthan.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(55, 5, 'Rolpa', N'रोल्पा', N'Liwang', N'लिवाङ्ग', N'1879', N'१८७९', N'https://dccrolpa.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(56, 5, 'Eastern Rukum', N'पूर्वी रूकुम', N'Rukumkot', N'रुकुमकोट', N'1161.13', N'११६१.१३', N'https://dccrukum.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(57, 5, 'Banke', N'बाँके', N'Nepalganj', N'नेपालगंज', N'2337', N'२३३७', N'https://dccbanke.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(58, 5, 'Bardiya', N'बर्दिया', N'Gulariya', N'गुलरिया', N'2025', N'२०२५', N'https://dccbardiya.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(59, 6, 'Western Rukum', N'रुकुम पश्चिम', N'Musikot', N'मुसिकोट', N'1213.49', N'१२१३.४९', N'https://dccrukum.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(60, 6, 'Salyan', N'सल्यान', N'Salyan', N'सल्यान', N'1462', N'१४६२', N'https://dccsalyan.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(61, 6, 'Dolpa', N'डोल्पा', N'Dunai', N'दुनै', N'7889', N'७८८९', N'https://dccdolpa.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(62, 6, 'Humla', N'हुम्ला', N'Simikot', N'सिमिकोट', N'5655', N'५६५५', N'https://dcchumla.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(63, 6, 'Jumla', N'जुम्ला', N'Chandannath', N'चन्दननाथ', N'2531', N'२५३१', N'https://dccjumla.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(64, 6, 'Kalikot', N'कालिकोट', N'Manma', N'मान्म', N'1741', N'१७४१', N'https://dcckalikot.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(65, 6, 'Mugu', N'मुगु', N'Gamgadhi', N'गमगढी', N'3535', N'३५३५', N'https://dccmugu.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(66, 6, 'Surkhet', N'सुर्खेत', N'Birendranagar', N'बिरेन्द्रनगर', N'2451', N'२४५१', N'https://dccsurkhet.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(67, 6, 'Dailekh', N'दैलेख', N'Dailekh', N'दैलेख', N'1502', N'१५०२', N'https://dccdailekh.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(68, 6, 'Jajarkot', N'जाजरकोट', N'Khalanga', N'खलंगा', N'2230', N'२२३०', N'https://dccjajarkot.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(69, 7, 'Darchula', N'दार्चुला', N'Darchula', N'दार्चुला', N'2344.61', N'२३४४.६१', N'https://ddcdarchula.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(70, 7, 'Bajhang', N'बझाङ', N'Jayaprithvi', N'जयप्रिथिवी', N'3394.21', N'३३९४.२१', N'https://dccbajhang.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(71, 7, 'Bajura', N'बाजुरा', N'Badimalika', N'बडिमालिका', N'2300.34', N'२३००.३४', N'https://dccbajura.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(72, 7, 'Baitadi', N'बैतडी', N'Dasharathchand', N'दशरथचन्द', N'1496.04', N'१४९६.०४', N'https://dccbaitadi.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(73, 7, 'Doti', N'डोटी', N'Dipayal Silgadhi', N'दिपायल सिलगढी', N'2295.71', N'२२९५.७१', N'https://dccdoti.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(74, 7, 'Acham', N'अछाम', N'Mangalsen', N'मंगलसेन', N'1692', N'१६९२', N'https://dccacham.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(75, 7, 'Dadeldhura', N'डडेलधुरा', N'Amargadhi', N'अमरगढी', N'1506.09', N'१५०६.०९', N'https://dccdadeldhura.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(76, 7, 'Kanchanpur', N'कञ्चनपुर', N'Bheemdatta', N'भीमदत्त', N'1222.31', N'१२२२.३१', N'https://dcckanchanpur.gov.np/', NULL, NULL, NULL, NULL, NULL ),
(77, 7, 'Kailali', N'कैलाली', N'Dhangadhi', N'धनगढी', N'3292.35', N'३२९२.३५', N'https://dcckailali.gov.np/', NULL, NULL, NULL, NULL, NULL )

